# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: python:3.10

pipelines:
  default:
    # The following deployment steps will be executed for each pipeline run. To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
    - step:
        name: 'Deployment to Staging'
        deployment: staging
        script:
          - echo "Your deployment to staging script goes here..."
    - step:
        name: Deploy to production
        deployment: production
        trigger: 'manual'
        script:
          - echo "Deploying to production environment"
#          - pipe: atlassian/ssh-run:0.2.2
          - mkdir -p ~/.ssh
          - echo $KNOWN_HOSTS > ~/.ssh/known_hosts
          - (umask  077 ; echo $DEPLOY_SSH_KEY | base64 -di > ~/.ssh/id_rsa)
          - ssh -i ~/.ssh/id_rsa $app_user@$app_server 'echo $USER && cd ~/apps/twitter2telegram && ~/apps/twitter2telegram/deploy.sh > ~/apps/twitter2telegram/deploy.out &'
